[Unit]
Requires=var-lib-bluetooth.mount rg40xxv-bluetooth-hci-ready.service
After=var-lib-bluetooth.mount rg40xxv-bluetooth-hci-ready.service systemd-rfkill.service

[Service]
ExecStartPre=/usr/sbin/rfkill unblock bluetooth
Restart=on-failure
RestartSec=2s
