#ifndef RG40XXV_COVER_LIMITS_H
#define RG40XXV_COVER_LIMITS_H

#include <stdint.h>

enum {
	COVER_SOURCE_MAX_WIDTH = 4096,
	COVER_SOURCE_MAX_HEIGHT = 4096,
	COVER_SOURCE_MAX_PIXELS = 4194304,
	COVER_DECODE_MAX_BYTES = 16777216,
	COVER_FILE_MAX_BYTES = 12582912,
	COVER_HEADER_SCAN_MAX_BYTES = 1048576,
	COVER_THUMBNAIL_MAX_WIDTH = 160,
	COVER_THUMBNAIL_MAX_HEIGHT = 232,
	COVER_NEARBY_CACHE_COUNT = 5,
	COVER_THUMBNAIL_MAX_BYTES = COVER_THUMBNAIL_MAX_WIDTH *
		COVER_THUMBNAIL_MAX_HEIGHT * 4,
	COVER_THUMBNAIL_CACHE_MAX_BYTES = COVER_THUMBNAIL_MAX_BYTES *
		COVER_NEARBY_CACHE_COUNT,
};

enum cover_probe_result {
	COVER_PROBE_OK = 0,
	COVER_PROBE_INVALID = -1,
	COVER_PROBE_LIMIT = -2,
	COVER_PROBE_IO = -3,
};

struct cover_dimensions {
	uint32_t width;
	uint32_t height;
	uint64_t decode_bytes;
};

int cover_probe_fd(int fd, uint64_t file_size, struct cover_dimensions *result);

#endif
